name: android-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Build Debug APK
        run: ./gradlew assembleDebug

  emulator-e2e:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_5
          script: |
            adb wait-for-device
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0

            # install app
            ./gradlew installDebug

            # ENABLE accessibility service (emulator mengizinkan via settings)
            PKG=com.example.desktopswitch
            SVC=$PKG/.DesktopSiteService
            adb shell settings put secure enabled_accessibility_services $SVC
            adb shell settings put secure accessibility_enabled 1

            # install Chrome stable di emulator (Play Store image biasanya sudah ada)
            # kalau belum ada, bisa pakai Chromium webview sebagai target test lain.

            # buka Chrome dan URL uji
            adb shell am start -n com.android.chrome/com.google.android.apps.chrome.Main \
              -a android.intent.action.VIEW -d "https://example.com"
            sleep 2

            # trigger lagi agar service bekerja beberapa kali
            adb shell input keyevent KEYCODE_APP_SWITCH
            adb shell input keyevent KEYCODE_APP_SWITCH
            sleep 2

            # (opsional) screenshot bukti
            adb exec-out screencap -p > screen.png
